# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f18b373c233e003d955b54a6868cf42a3dc8bc2b5c241eee5d1828f58ac4c46148f3f1f766353217b52bbd078c3f66aea7b919bc64382003fdad12c6c43ca838

test:
  secret_key_base: 89bd2334a7a410a8fbf9be6f65c3a6f1ad771e0a564fe184c660afc8f55ee56ca2921c4abb1f950e3aa8a7a6bc328f33bb9fc18bb87d45b28cd472bf1f2402ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
